/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard_Admin;
import java.awt.Dimension;
import java.awt.Component;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {
private boolean isCollapsed = false;
private int sidebarWidth = 200;
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null); 
        dLogout.setBackground(new java.awt.Color(200, 60, 60));
        setSidebarRapi(sidebarWidth);
        styleMenu(ddashboard);
        dLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dLogout.setIconTextGap(0);

        setPanel(new menu_dashboard());
    }

    public Dashboard(String user) {
        initComponents();
        dLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
dLogout.setIconTextGap(0);
        setLocationRelativeTo(null); 
        lblUser.setText(user);
        setSidebarRapi(sidebarWidth);
        styleMenu(ddashboard);
        styleMenu(dDataSiswa);
        styleMenu(dDataGuru);
        styleMenu(dMataPelajaran);
        styleMenu(dDataKelas);
        styleMenu(dJadwalPelajaran);
        styleMenu(dAbsensi);
        styleMenu(dNilaiUjian);
        styleMenu(dLogout);
        setPanel(new menu_dashboard());
    }
    
    private void setPanel(javax.swing.JPanel panel) {
    jPanel4.removeAll();
    jPanel4.setLayout(new java.awt.BorderLayout());
    jPanel4.add(panel, java.awt.BorderLayout.CENTER);
    jPanel4.revalidate();
    jPanel4.repaint();
}
    
  private void setSidebarRapi(int width) {
    Dimension size = new Dimension(width - 20, 45);

    javax.swing.JButton[] menus = {
        ddashboard, dDataSiswa, dDataGuru,
        dMataPelajaran, dDataKelas,
        dJadwalPelajaran, dAbsensi, dNilaiUjian, dLogout
    };

    for (javax.swing.JButton btn : menus) {
        btn.setMaximumSize(size);
        btn.setMinimumSize(size);
        btn.setPreferredSize(size);
        btn.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        
    }
}
    
   private void toggleSidebar() {
    int targetWidth = isCollapsed ? 200 : 60;

    javax.swing.Timer timer = new javax.swing.Timer(5, null);
    timer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            if (!isCollapsed) {
                sidebarWidth -= 10;
                if (sidebarWidth <= targetWidth) {
                    sidebarWidth = targetWidth;
                    timer.stop();
                    isCollapsed = true;
                }
            } else {
                sidebarWidth += 10;
                if (sidebarWidth >= targetWidth) {
                    sidebarWidth = targetWidth;
                    timer.stop();
                    isCollapsed = false;
                }
            }

            // ⬇️ resize sidebar
            jPanel1.setPreferredSize(new java.awt.Dimension(sidebarWidth, getHeight()));
            setSidebarRapi(sidebarWidth);
            jPanel1.revalidate();

            // 
            if (sidebarWidth <= 80) {
                setMenuCollapse(true);
                jPanel6.setVisible(false);
            } else {
                setMenuCollapse(false);
                jPanel6.setVisible(true);

                ddashboard.setText("Dashboard");
                dDataSiswa.setText("Data Siswa");
                dDataGuru.setText("Data Guru");
                dMataPelajaran.setText("Mata Pelajaran");
                dDataKelas.setText("Data Kelas");
                dJadwalPelajaran.setText("Jadwal Pelajaran");
                dAbsensi.setText("Absensi");
                dNilaiUjian.setText("Nilai Ujian");
                dLogout.setText("Logout");
            }
        }
    });
    timer.start();
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ddashboard = new javax.swing.JButton();
        dDataSiswa = new javax.swing.JButton();
        dDataGuru = new javax.swing.JButton();
        dMataPelajaran = new javax.swing.JButton();
        dDataKelas = new javax.swing.JButton();
        dJadwalPelajaran = new javax.swing.JButton();
        dAbsensi = new javax.swing.JButton();
        dNilaiUjian = new javax.swing.JButton();
        dLogout = new javax.swing.JButton();
        dNilaiUjian1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        dtbldashboard = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 61, 142));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 464));

        jPanel6.setBackground(new java.awt.Color(25, 61, 142));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 45));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/departemen-pendidikan-nasional-seeklogo (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIAKAD SMP");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(25, 61, 142));

        ddashboard.setBackground(new java.awt.Color(25, 61, 142));
        ddashboard.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ddashboard.setForeground(new java.awt.Color(255, 255, 255));
        ddashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-dashboard-layout-20.png"))); // NOI18N
        ddashboard.setText("Dashboard");
        ddashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddashboardActionPerformed(evt);
            }
        });

        dDataSiswa.setBackground(new java.awt.Color(25, 61, 142));
        dDataSiswa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        dDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-group-20.png"))); // NOI18N
        dDataSiswa.setText("Data Siswa");
        dDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDataSiswaActionPerformed(evt);
            }
        });

        dDataGuru.setBackground(new java.awt.Color(25, 61, 142));
        dDataGuru.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        dDataGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-graduation-cap-20.png"))); // NOI18N
        dDataGuru.setText("Data Guru");
        dDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDataGuruActionPerformed(evt);
            }
        });

        dMataPelajaran.setBackground(new java.awt.Color(25, 61, 142));
        dMataPelajaran.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dMataPelajaran.setForeground(new java.awt.Color(255, 255, 255));
        dMataPelajaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-book-20.png"))); // NOI18N
        dMataPelajaran.setText("Mata Pelajaran");
        dMataPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dMataPelajaranActionPerformed(evt);
            }
        });

        dDataKelas.setBackground(new java.awt.Color(25, 61, 142));
        dDataKelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dDataKelas.setForeground(new java.awt.Color(255, 255, 255));
        dDataKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-school-20 (1).png"))); // NOI18N
        dDataKelas.setText("Data Kelas");
        dDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDataKelasActionPerformed(evt);
            }
        });

        dJadwalPelajaran.setBackground(new java.awt.Color(25, 61, 142));
        dJadwalPelajaran.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dJadwalPelajaran.setForeground(new java.awt.Color(255, 255, 255));
        dJadwalPelajaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-schedule-20.png"))); // NOI18N
        dJadwalPelajaran.setText("Jadwal Pelajaran");
        dJadwalPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dJadwalPelajaranActionPerformed(evt);
            }
        });

        dAbsensi.setBackground(new java.awt.Color(25, 61, 142));
        dAbsensi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        dAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-what-i-do-20.png"))); // NOI18N
        dAbsensi.setText("Absensi");
        dAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAbsensiActionPerformed(evt);
            }
        });

        dNilaiUjian.setBackground(new java.awt.Color(25, 61, 142));
        dNilaiUjian.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dNilaiUjian.setForeground(new java.awt.Color(255, 255, 255));
        dNilaiUjian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-exam-20.png"))); // NOI18N
        dNilaiUjian.setText("Nilai Ujian & Raport");
        dNilaiUjian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNilaiUjianActionPerformed(evt);
            }
        });

        dLogout.setBackground(new java.awt.Color(25, 61, 142));
        dLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dLogout.setForeground(new java.awt.Color(255, 255, 255));
        dLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-20.png"))); // NOI18N
        dLogout.setText("Logout");
        dLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLogoutActionPerformed(evt);
            }
        });

        dNilaiUjian1.setBackground(new java.awt.Color(25, 61, 142));
        dNilaiUjian1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dNilaiUjian1.setForeground(new java.awt.Color(255, 255, 255));
        dNilaiUjian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-20.png"))); // NOI18N
        dNilaiUjian1.setText("Nilai Siswa");
        dNilaiUjian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNilaiUjian1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddashboard)
                    .addComponent(dDataSiswa)
                    .addComponent(dDataGuru)
                    .addComponent(dMataPelajaran)
                    .addComponent(dDataKelas)
                    .addComponent(dJadwalPelajaran)
                    .addComponent(dAbsensi)
                    .addComponent(dNilaiUjian)
                    .addComponent(dLogout)
                    .addComponent(dNilaiUjian1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(ddashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dDataSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dDataGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dMataPelajaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dDataKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dJadwalPelajaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dNilaiUjian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dNilaiUjian1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(dLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(1150, 615));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(648, 45));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Dashboard");

        dtbldashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-menu-20.png"))); // NOI18N
        dtbldashboard.setPreferredSize(new java.awt.Dimension(0, 0));
        dtbldashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtbldashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dtbldashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(378, 378, 378)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtbldashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(888, 490));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDataSiswaActionPerformed
        // TODO add your handling code here:
        form_siswa fs = new form_siswa();
    fs.showPanel("view"); // atau "add"
    setPanel(fs);
    }//GEN-LAST:event_dDataSiswaActionPerformed

    private void ddashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddashboardActionPerformed
        // TODO add your handling code here:
        setPanel(new menu_dashboard());
        
    }//GEN-LAST:event_ddashboardActionPerformed

    private void dDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDataGuruActionPerformed
        // TODO add your handling code here:
        setPanel(new form_guru());
    }//GEN-LAST:event_dDataGuruActionPerformed

    private void dMataPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dMataPelajaranActionPerformed
        // TODO add your handling code here:
        setPanel(new form_mapel());
    }//GEN-LAST:event_dMataPelajaranActionPerformed

    private void dDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDataKelasActionPerformed
        // TODO add your handling code here:
        setPanel(new form_kelas());
    }//GEN-LAST:event_dDataKelasActionPerformed

    private void dJadwalPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dJadwalPelajaranActionPerformed
        // TODO add your handling code here:
        setPanel(new form_japel());
    }//GEN-LAST:event_dJadwalPelajaranActionPerformed

    private void dAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAbsensiActionPerformed
        // TODO add your handling code here:
        setPanel(new form_absensi());
    }//GEN-LAST:event_dAbsensiActionPerformed

    private void dNilaiUjianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNilaiUjianActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dNilaiUjianActionPerformed

    private void dtbldashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtbldashboardActionPerformed
        // TODO add your handling code here:
        toggleSidebar();
    
    }//GEN-LAST:event_dtbldashboardActionPerformed

    private void dLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLogoutActionPerformed
        // TODO add your handling code here:
       int confirm = javax.swing.JOptionPane.showConfirmDialog(
    this,
    "Yakin mau logout?",
    "Konfirmasi",
    javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    new tampilan.loginform().setVisible(true);
dispose();
}
    }//GEN-LAST:event_dLogoutActionPerformed

    private void dNilaiUjian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNilaiUjian1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNilaiUjian1ActionPerformed
private void styleMenu(javax.swing.JButton btn) {
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    btn.setForeground(java.awt.Color.WHITE);
    btn.setBackground(new java.awt.Color(25, 61, 142));
    btn.setFocusPainted(false);

    // 🔥 khusus logout
    if (btn == dLogout) {
        btn.setBorderPainted(true);
    } else {
        btn.setBorderPainted(false);
    }

    btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btn.setIconTextGap(10);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 10));
}

private void setMenuCollapse(boolean collapse) {
    javax.swing.JButton[] menus = {
        ddashboard, dDataSiswa, dDataGuru,
        dMataPelajaran, dDataKelas,
        dJadwalPelajaran, dAbsensi, dNilaiUjian, dLogout
    };

    for (javax.swing.JButton btn : menus) {
        if (collapse) {
            btn.setText("");
            btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            btn.setIconTextGap(0);

            if (btn == dLogout) {
                btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 80, 80)));
            } else {
                btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
            }

        } else {
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setIconTextGap(10);

            if (btn == dLogout) {
                btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 80, 80)));
            } else {
                btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 10));
            }
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dAbsensi;
    private javax.swing.JButton dDataGuru;
    private javax.swing.JButton dDataKelas;
    private javax.swing.JButton dDataSiswa;
    private javax.swing.JButton dJadwalPelajaran;
    private javax.swing.JButton dLogout;
    private javax.swing.JButton dMataPelajaran;
    private javax.swing.JButton dNilaiUjian;
    private javax.swing.JButton dNilaiUjian1;
    private javax.swing.JButton ddashboard;
    private javax.swing.JButton dtbldashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
